--  NOTE: Must happen before plugins are required (otherwise wrong leader will be used)
vim.g.mapleader = " "
vim.g.maplocalleader = " "

require("Options.Options")
require("Options.Netrw")
require("Install.Requirements")
require("Config.Onedark")
require("Config.Lualine")
require("Config.Telescope")
require("Config.Treesitter")
require("Config.Lsp")
require("Config.Blink")
require("Config.Diagnostics")
require("Config.Gitsigns")
require("Config.Harpoon")
require("Config.Ibl")
require("Config.Debug")
require("Config.Which")
require("Config.Mini.Icons")
require('Config.Mini.Map')
require("Config.Mini.Pairs")
require('Config.Mini.Surround')
require('Config.Mini.Comment')
require('Config.Mini.Leap')
-- require("Config.Mini.Starter")
-- require("Config.Mini.Around")

-- require("Config.AI")
-- require('Config.Conform')
-- require("Config.Braces")
-- require("Config.Cmnt")

-- require("Remaps.Autosave")
require("Remaps.Debug")
require("Remaps.Diagnostics")
require("Remaps.Git")
require("Remaps.Netrw")
require("Remaps.Remaps")
require("Remaps.Splits")
require("Remaps.Tabs")
require("Remaps.Telescope")
require("Remaps.Terminals")
