--  NOTE: Must happen before plugins are required (otherwise wrong leader will be used)
vim.g.mapleader = " "
vim.g.maplocalleader = " "

require("Options.Options")
require("Options.Netrw") -- Not ready yet
require("Install.Requirements")
require("Config.Onedark")
require("Config.Lualine")
require("Config.Telescope")
require("Config.Treesitter")
require("Config.AI")
require("Config.Lsp")
require("Config.Blink")
require("Config.Diagnostics")
-- require('Config.Conform')
require("Config.Braces")
require("Config.Gitsigns")
require("Config.Harpoon")
require("Config.Ibl")
require("Config.Mini")
require("Config.Which")
require("Config.Cmnt")
require("Config.Debug")
-- require("Remaps.Autosave") -- Disabled since this will cause marco's to run slower
require("Remaps.Debug")
require("Remaps.Diagnostics")
require("Remaps.Git")
-- require("Remaps.Harpoon")
require("Remaps.Netrw")
require("Remaps.Remaps")
require("Remaps.Splits")
require("Remaps.Tabs")
require("Remaps.Telescope")
require("Remaps.Terminals")
